### PR TITLE
Implement touchpad_disables_numpad support on KDE with qdbus

### PR DESCRIPTION
**Pull request by sleddev**

### CODE REVIEW

**Comment by ldrahnik** [comment]
@sleddev I had to make a few improvements so I pushed commit directly to the master branch. Look at that and confirm it works, please :)

**Comment by sleddev** [comment]
> @sleddev I had to make a few improvements so I pushed commit directly to the master branch. Look at that and confirm it works, please :)

Yes it works great

**Comment by sleddev** [comment]
@ldrahnik But I noticed a bug regarding disabling the touchpad.

When the touchpad is disabled, and I try to turn the numpad on, it won't turn on, as expected. But if I then enable the touchpad, and try to turn on the numpad again, the whole driver will freeze.

It gets stuck at `numlock_lock.acquire()` in line 1390, in function `local_numlock_pressed`.

This is because the lock doesn't get released when the touchpad is disabled. A `numlock_lock.release()` before returning in line 1395 fixes this.

**Comment by ldrahnik** [comment]
@sleddev Commited. Thank you (y)

**Pull request closed without merging**
